- name: Create C:\temp directory
  win_file:
    path: C:\temp
    state: directory

- name: Copy Notepad++ installer to target
  win_copy:
    src: /home/vvolf/Ansible/Windows-Automation/Windows-10and11-Desktop/roles/App_install/files/npp.8.7.9.Installer.x64.exe
    dest: C:\temp\npp.8.7.9.Installer.x64.exe

- name: Copy Zabbix-Agent installer to target
  win_copy:
    src: /home/vvolf/Ansible/Windows-Automation/Windows-10and11-Desktop/roles/App_install/files/zabbix_agent-7.2.5-windows-amd64-openssl.zip
    dest: C:\temp\zabbix_agent-7.2.5-windows-amd64-openssl.zip

- name: Copy Wireshark installer to target
  win_copy:
    src: /home/vvolf/Ansible/Windows-Automation/Windows-10and11-Desktop/roles/App_install/files/Wireshark-4.4.5-x64.exe
    dest: C:\temp\Wireshark-4.4.5-x64.exe

- name: Copy WinSCP installer to target
  win_copy:
    src: /home/vvolf/Ansible/Windows-Automation/Windows-10and11-Desktop/roles/App_install/files/WinSCP-6.5-Portable.zip
    dest: C:\temp\WinSCP-6.5-Portable.zip

- name: Copy Google Chrome installer to target
  win_copy:
    src: /home/vvolf/Ansible/Windows-Automation/Windows-10and11-Desktop/roles/App_install/files/chrome_installer.exe
    dest: C:\temp\chrome_installer.exe
