---
- name: Install AD-Domain-Services and DNS roles
  win_feature:
    name:
      - AD-Domain-Services
      - DNS
    include_management_tools: yes
    state: present
  register: feature_result

- name: Reboot after feature installation
  win_reboot:
    reboot_timeout: 600
  when: feature_result.changed

- name: Promote server to Domain Controller
  microsoft.ad.domain:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_netbios_name: "{{ domain_netbios_name }}"
    safe_mode_password: "{{ domain_safe_mode_password }}"
  register: domain_results

- name: Reboot after domain promotion
  win_reboot:
    reboot_timeout: 600
  when: domain_results.changed

- name: Ensure reverse DNS zone exists
  ansible.windows.win_dns_zone:
    name: "{{ item.zone_name | trim }}"
    type: primary
    replication: domain
    dynamic_update: secure
    state: present
  loop: "{{ reverse_zones }}"
